baseurl = "https://homerlab.com.br"
languageCode = "br"
defaultContentLanguage = "br"
theme = "hugo-theme-hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.br]
    title = "Homer Lab Brasil"
    subtitle = "Blog Homerlab Brasil | Blog sobre Automação, Segurança da Informação, Infraestrutura de TI, Virtualização, Cloud, DevOps"
    keywords = "Automação, Segurança da Informação, Infraestrutura de TI, Virtualização, Cloud, DevOps"
    copyright = "2021-2022 - Homer Lab Brasil - Allan Lopes"
    menuMore = "Mostrar mais"
    writtenBy = "Escrito por"
    readMore = "Ler mais"
    readOtherPosts = "Leia outras postagens"
    newerPosts = "Novas postagens"
    olderPosts = "Antigas postagens"
    minuteReadingTime = "min de leitura"
    dateFormatSingle = "02/01/2006"
    dateFormatList = "02/01/2006"

    [languages.br.params.logo]
      logoText = "Homer Lab Brasil"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.br.menu]
      [[languages.br.menu.main]]
        identifier = "sobre"
        name = "Sobre"
        url = "/sobre"

      #[[languages.en.menu.main]]
      #  identifier = "showcase"
      #  name = "Mostruário"
      #  url = "/showcase"

      [[languages.br.menu.main]]
        identifier = "arquivo"
        name = "Arquivo"
        url = "/arquivo"
