baseURL = 'https://homerlab.com.br/'
languageCode = "br"
defaultContentLanguage = "br"
title = 'Homer Lab'
theme = 'hello-friend'

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 10
  # Enable to show reading time in minutes for posts
  showReadingTime = true
  socialShare = true ## mostrar o social share
  author = "Allan Lopes"
  #logo_1 = "/img/veeam-vanguard-logo.png"
  #logo_2 = "/img/vmware-vexpert-logo.png"
  metadescription = "Blog Homer Lab Brasil"
  defaultimage = "/img/homelaber-twiiter-card-1200x675.png"
