baseurl = "https://homerlab.com.br"
languageCode = "br"
theme = "hugo-theme-hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.br]
    title = "Hello Friend"
    subtitle = "Blog Homerlab Brasil | Homer Lab· Infraestrutura de TI· Virtualização· Cloud Computing · DevOps | Blog sobre Virtualização, Infraestrutura de TI, Cloud Computing e DevOps escrito em Português. Criado e editado por Allan Lopes"
    keywords = "Blog, Infraestrutura, TI Corporativa, Virtualização, Veeam, Backup, Cloud, Cloud Computing, Cloud Native"
    copyright = "2021-2022 - Homer Lab Brasil - Allan Lopes"
    menuMore = "Mostrar mais"
    writtenBy = "Escrito por"
    readMore = "Ler mais"
    readOtherPosts = "Ler outros posts"
    newerPosts = "Novos posts"
    olderPosts = "Antigos posts"
    minuteReadingTime = "min lendo"
    	  wordCount = "palavras"
    dateFormatSingle = "02-01-2006"
    dateFormatList = "02-01-2006"

    [languages.en.params.logo]
      logoText = "Homer Lab Brasil"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "Sobre"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Mostruário"
        url = "/showcase"

      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Arquivo"
        url = "/archive"
